
import java.awt.HeadlessException;
import java.awt.print.PrinterException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author vedantgrover
 */
public class Certificates extends javax.swing.JFrame {
    Connection con; 

    /**
     * Creates new form Certificates
     */
    public Certificates() {
        initComponents();
        con = Connect.ConnecrDB();
    }
    
    ArrayList<ClientsCertificates> MasteredClientsList = new ArrayList();  
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        BackToMenuButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        PrintingTable = new javax.swing.JTable();
        PrintButton = new javax.swing.JButton();
        UpdateTableButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        ClientNameLabel = new javax.swing.JLabel();
        TopicNameLabel = new javax.swing.JLabel();
        CertificateLabel = new javax.swing.JLabel();
        Certificate = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel1.setText("People who've mastered a topic:");

        BackToMenuButton.setBackground(new java.awt.Color(255, 255, 255));
        BackToMenuButton.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        BackToMenuButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Screen Shot 2018-03-16 at 12.20.01 PM.png"))); // NOI18N
        BackToMenuButton.setText("To menu");
        BackToMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackToMenuButtonActionPerformed(evt);
            }
        });

        PrintingTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Client Name", "Topic"
            }
        ));
        PrintingTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PrintingTableMouseClicked(evt);
            }
        });
        PrintingTable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PrintingTableKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(PrintingTable);

        PrintButton.setBackground(new java.awt.Color(255, 255, 255));
        PrintButton.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        PrintButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Screen Shot 2018-09-11 at 9.11.11 AM.png"))); // NOI18N
        PrintButton.setText("Certificate\n");
        PrintButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrintButtonActionPerformed(evt);
            }
        });

        UpdateTableButton.setBackground(new java.awt.Color(255, 255, 255));
        UpdateTableButton.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        UpdateTableButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Screen Shot 2018-03-17 at 11.50.32 AM.png"))); // NOI18N
        UpdateTableButton.setText("Table\n");
        UpdateTableButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateTableButtonActionPerformed(evt);
            }
        });

        jPanel2.setLayout(null);

        ClientNameLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jPanel2.add(ClientNameLabel);
        ClientNameLabel.setBounds(380, 240, 160, 30);

        TopicNameLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jPanel2.add(TopicNameLabel);
        TopicNameLabel.setBounds(350, 380, 150, 30);

        CertificateLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Screen Shot 2018-09-17 at 1.04.45 AM.png"))); // NOI18N
        jPanel2.add(CertificateLabel);
        CertificateLabel.setBounds(0, 0, 790, 600);

        Certificate.setColumns(20);
        Certificate.setRows(5);
        jPanel2.add(Certificate);
        Certificate.setBounds(0, 0, 790, 600);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(UpdateTableButton, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(BackToMenuButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(PrintButton, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 786, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PrintButton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UpdateTableButton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BackToMenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackToMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackToMenuButtonActionPerformed
        dispose();
        MainMenu mm = new MainMenu();
        //Connect.closeConnection(con);
        mm.setVisible(true);
        //this.setVisible(false);
    }//GEN-LAST:event_BackToMenuButtonActionPerformed

    private void PrintButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrintButtonActionPerformed
        
        try {
            Certificate.print();
        } catch (PrinterException ex) {
            Logger.getLogger(Certificates.class.getName()).log(Level.SEVERE, null, ex);
        }
 
    }//GEN-LAST:event_PrintButtonActionPerformed

    private void UpdateTableButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateTableButtonActionPerformed
        String query = "SELECT Name, TopicName FROM People JOIN Link on People.Id = Link.Person_ID JOIN "
                + "Content on Link.TopicNo = Content.TopicNo WHERE Link.LevelOnTopic > 4 AND People.Id < 110";
       //join function used again to retrieve the clients who have mastered topics by selecting all the clients 
       //who have a skill level on a topic higher than 4(ie 5)
        PreparedStatement pst;
        ResultSet rs;
        try {
            pst = con.prepareStatement(query);
            rs = pst.executeQuery();
            //values stored in resultset
            while (rs.next()) {
                ClientsCertificates Client = new ClientsCertificates();
                Client.setName(rs.getString("Name"));
                Client.setTopicName(rs.getString("TopicName"));
                MasteredClientsList.add(Client);
                
                //now added to arraylist using the certificates class shown previously 
                
            }
            pst.close();
            con.commit();
        } 
        catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(null, e);

        }
        
        
        DefaultTableModel model = (DefaultTableModel) PrintingTable.getModel();
        PrintingTable.setRowHeight(50);
        Object rowData[] = new Object[2];
        for (int i = 0; i < MasteredClientsList.size(); i++) {
            rowData[0] = MasteredClientsList.get(i).getName();
            rowData[1] = MasteredClientsList.get(i).getTopicName();
            //values from arraylist put into table 
            model.addRow(rowData);
        }
        
    }//GEN-LAST:event_UpdateTableButtonActionPerformed

    private void PrintingTableKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PrintingTableKeyPressed
        // TODO add your handling code here:
        int i = PrintingTable.getSelectedRow();
        TableModel model = PrintingTable.getModel();
        ClientNameLabel.setText(model.getValueAt(i, 0).toString());
        TopicNameLabel.setText(model.getValueAt(i, 1).toString());
        
    }//GEN-LAST:event_PrintingTableKeyPressed

    private void PrintingTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PrintingTableMouseClicked
        // TODO add your handling code here:
        int i = PrintingTable.getSelectedRow();
        TableModel model = PrintingTable.getModel();
        ClientNameLabel.setText(model.getValueAt(i, 0).toString());
        TopicNameLabel.setText(model.getValueAt(i, 1).toString());
    }//GEN-LAST:event_PrintingTableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Certificates.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Certificates.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Certificates.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Certificates.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Certificates().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackToMenuButton;
    private javax.swing.JTextArea Certificate;
    private javax.swing.JLabel CertificateLabel;
    private javax.swing.JLabel ClientNameLabel;
    private javax.swing.JButton PrintButton;
    private javax.swing.JTable PrintingTable;
    private javax.swing.JLabel TopicNameLabel;
    private javax.swing.JButton UpdateTableButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
