
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
import java.sql.Connection;
import java.sql.*;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.renderer.category.BarRenderer;
import org.jfree.data.jdbc.JDBCCategoryDataset;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author vedantgrover
 */
public class DataChart extends javax.swing.JFrame {
    Connection con; 

    /**
     * Creates new form DataChart
     */
    public DataChart() {
        initComponents();
        con = Connect.ConnecrDB();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        SkillLevelChartButton = new javax.swing.JButton();
        PassionLevelChartButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        BackToMenuButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TopicList = new javax.swing.JList<>();
        TopicNameTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        SkillLevelChartButton.setBackground(new java.awt.Color(255, 255, 255));
        SkillLevelChartButton.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        SkillLevelChartButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Screen Shot 2018-10-07 at 11.55.00 PM.png"))); // NOI18N
        SkillLevelChartButton.setText("For Skill Level\n");
        SkillLevelChartButton.setPreferredSize(new java.awt.Dimension(141, 74));
        SkillLevelChartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SkillLevelChartButtonActionPerformed(evt);
            }
        });

        PassionLevelChartButton.setBackground(new java.awt.Color(255, 255, 255));
        PassionLevelChartButton.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        PassionLevelChartButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Screen Shot 2018-10-07 at 11.55.00 PM.png"))); // NOI18N
        PassionLevelChartButton.setText("For Passion Level\n\n");
        PassionLevelChartButton.setPreferredSize(new java.awt.Dimension(227, 74));
        PassionLevelChartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PassionLevelChartButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jLabel1.setText("Choose a topic:");

        BackToMenuButton.setBackground(new java.awt.Color(255, 255, 255));
        BackToMenuButton.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        BackToMenuButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Screen Shot 2018-03-16 at 12.20.01 PM.png"))); // NOI18N
        BackToMenuButton.setText("To menu");
        BackToMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackToMenuButtonActionPerformed(evt);
            }
        });

        TopicList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "﻿", "Basic Skills", "Spotlight", "Pages", "Typing", "Keynote", "Photo Booth", "iMovie", "Google Maps", "Photoshop", "Notes", "Eclipse", "Garage Band", "Yenka", "Netbeans", "Google drive", "Youtube", "Gmail", "Online games", "Excel", "Google Calendar", "Teamie", "Onenote", "iTunes", "Spotify", "Movie streaming", "App store", "Chrome webstore", "Skype", "Facebook", "Creately", "Terminal", "Sketchup", "Fusion", "Yenka", "VLC", "Quicktime player", "Time machine", "Dictionary", "Self control", "Logger pro", "Numbers", "Calculator", "Text edit", "System preferences", "SQLite", "Ti-nspire", "Draw.io", "Google search", "Twitter", "Instagram" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        TopicList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TopicListMouseClicked(evt);
            }
        });
        TopicList.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TopicListKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(TopicList);

        TopicNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TopicNameTextFieldActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel2.setText("Graph:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(TopicNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BackToMenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(PassionLevelChartButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SkillLevelChartButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TopicNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(PassionLevelChartButton, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(SkillLevelChartButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(BackToMenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackToMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackToMenuButtonActionPerformed
        dispose();
        MainMenu mm = new MainMenu();
        //Connect.closeConnection(con);
        mm.setVisible(true);
        //this.setVisible(false);
    }//GEN-LAST:event_BackToMenuButtonActionPerformed

    private void PassionLevelChartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PassionLevelChartButtonActionPerformed
        // TODO add your handling code here:
        try {
            //Class.forName("org.sqlite.JDBC"); 
            //Connection con = DriverManager.getConnection("jdbc:sqlite:/Users/vedantgrover/Desktop/internalassessment.db");
            //String query = "SELECT Name, PassionLevel FROM People join Link on People.Id = Link.Person_ID join Content on "
                   // + "Link.TopicNo = Content.TopicNo where Content.TopicName = ? & People.Id < 110";
            
            //Join function used to retrieve names and passion levels for all clients on each topic to display 
            String query = "Select Name, PassionLevel from ChartData where TopicNo = 2 AND Person_ID < 110";
            //PreparedStatement pst = con.prepareStatement(query);
            //pst.setString(1, TopicNameTextField.getText());
            
            JDBCCategoryDataset dataset = new JDBCCategoryDataset(Connect.ConnecrDB(), query);
            JFreeChart chart = ChartFactory.createLineChart("Passion Level Chart for " + TopicNameTextField.getText() ,
                    "Client Name", "Passion Level", dataset, PlotOrientation.VERTICAL, false, true, true);
            //the x-axis and y-axis headings for the graph 
            BarRenderer renderer = null; 
            CategoryPlot plot = null; 
            renderer = new BarRenderer(); 
            ChartFrame frame = new ChartFrame("Passion Level Chart for " + TopicNameTextField.getText(), chart);
            frame.setVisible(true);
            frame.setSize(1000,700); 
            //size of graph 
            
            con.commit();
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
    }//GEN-LAST:event_PassionLevelChartButtonActionPerformed

    private void SkillLevelChartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SkillLevelChartButtonActionPerformed
        // TODO add your handling code here:
        
        try {
            //Class.forName("org.sqlite.JDBC"); 
            //Connection con = DriverManager.getConnection("jdbc:sqlite:/Users/vedantgrover/Desktop/internalassessment.db");
            //String query = "SELECT Name, LevelOnTopic FROM People join Link on People.Id = Link.Person_ID join Content on Link.TopicNo = Content.TopicNo where Content.TopicName = ? & People.Id < 110";
            String query = "Select Name, LevelOnTopic from ChartData where TopicNo = 2 AND Person_ID < 110";
            
            //PreparedStatement pst = con.prepareStatement(query);
            //pst.setString(1, TopicNameTextField.getText());
            
            
            JDBCCategoryDataset dataset = new JDBCCategoryDataset(Connect.ConnecrDB(), query);
            JFreeChart chart = ChartFactory.createLineChart("Skill Level Chart for " + TopicNameTextField.getText() , "Client Name", "Skill Level", dataset, PlotOrientation.VERTICAL, false, true, true);
            BarRenderer renderer = null; 
            CategoryPlot plot = null; 
            renderer = new BarRenderer(); 
            ChartFrame frame = new ChartFrame("Skill Level Chart for " + TopicNameTextField.getText(), chart);
            frame.setVisible(true);
            frame.setSize(1000,700); 
            
            con.commit();
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_SkillLevelChartButtonActionPerformed

    private void TopicNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TopicNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TopicNameTextFieldActionPerformed

    private void TopicListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TopicListMouseClicked
        // TODO add your handling code here:
        TopicNameTextField.setText(TopicList.getSelectedValue());
    }//GEN-LAST:event_TopicListMouseClicked

    private void TopicListKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TopicListKeyReleased
        // TODO add your handling code here:
        TopicNameTextField.setText(TopicList.getSelectedValue());

    }//GEN-LAST:event_TopicListKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataChart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataChart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataChart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataChart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataChart().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackToMenuButton;
    private javax.swing.JButton PassionLevelChartButton;
    private javax.swing.JButton SkillLevelChartButton;
    private javax.swing.JList<String> TopicList;
    private javax.swing.JTextField TopicNameTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
