
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.*; 
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import java.util.ArrayList;
import javax.swing.table.TableColumnModel;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author vedantgrover
 */
public class Link extends javax.swing.JFrame {
    Connection con;

    /**
     * Creates new form Link
     */
    public Link() {
        initComponents();
        con = Connect.ConnecrDB();
        show_user(); 
        
    }
    public ArrayList<LinkUser> LinkList(){
        ArrayList<LinkUser> usersList = new ArrayList<>(); 
        try{
            Class.forName("org.sqlite.JDBC"); 
            Connection con = DriverManager.getConnection("jdbc:sqlite:/Users/vedantgrover/Desktop/internalassessment.db"); 
            String query1="SELECT * FROM Link";
            Statement s = con.createStatement();
            TableColumnModel columnModel = LinkTable.getColumnModel();
            columnModel.getColumn(0).setPreferredWidth(1200);
            columnModel.getColumn(1).setPreferredWidth(1300);
            columnModel.getColumn(2).setPreferredWidth(1200);
            columnModel.getColumn(3).setPreferredWidth(1200);
            columnModel.getColumn(4).setPreferredWidth(1200);
            LinkTable.setRowHeight(45);
            ResultSet rs = s.executeQuery(query1);
            LinkUser user; 
            while (rs.next()){
                user = new LinkUser(rs.getInt("LinkNo"),rs.getInt("Person_ID"), rs.getInt("TopicNo"), rs.getInt("LevelOnTopic"), rs.getInt("PassionLevel")); 
                usersList.add(user);   
            }   
            
            //s.close();
        }
        catch(ClassNotFoundException | SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
        return usersList; 
    }
    public void show_user(){
        ArrayList<LinkUser> list = LinkList();
        DefaultTableModel model = (DefaultTableModel)LinkTable.getModel();
        Object[] row = new Object[5];
        for(int i=0; i<list.size(); i++ ){
            row[0] = list.get(i).getLinkNo();
            row[1] = list.get(i).getPerson_ID();
            row[2] = list.get(i).getTopicNo();
            row[3] = list.get(i).getLevelOnTopic();
            row[4] = list.get(i).getPassionLevel();
            model.addRow(row);
        }
    
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel13 = new javax.swing.JLabel();
        jSpinner2 = new javax.swing.JSpinner();
        jPanel1 = new javax.swing.JPanel();
        LevelOnTopicLabel = new javax.swing.JLabel();
        TopicNoTextField = new javax.swing.JTextField();
        Person_IDTextField = new javax.swing.JTextField();
        TitleLabel = new javax.swing.JLabel();
        LevelOnTopicjSpinner = new javax.swing.JSpinner();
        TopicNoLabel = new javax.swing.JLabel();
        Person_IDLabel = new javax.swing.JLabel();
        SearchTextField = new javax.swing.JTextField();
        SearchLinkButton = new javax.swing.JButton();
        AddLinkButton = new javax.swing.JButton();
        UpdateLinkButton = new javax.swing.JButton();
        DeleteLinkButton = new javax.swing.JButton();
        BackToMenuButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        LinkTable = new javax.swing.JTable();
        LinkNoLabel = new javax.swing.JLabel();
        LinkNoTextField = new javax.swing.JTextField();
        PassionLevelLabel = new javax.swing.JLabel();
        PassionLeveljSpinner = new javax.swing.JSpinner();

        jLabel13.setText("LevelOnTopic");

        jSpinner2.setModel(new javax.swing.SpinnerListModel(new String[] {"1", "2", "3", "4", "5"}));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        LevelOnTopicLabel.setText("LevelOnTopic");

        TitleLabel.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        TitleLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Screen Shot 2018-03-16 at 11.50.01 AM.png"))); // NOI18N
        TitleLabel.setText("Link table");

        LevelOnTopicjSpinner.setModel(new javax.swing.SpinnerListModel(new String[] {"1", "2", "3", "4", "5"}));

        TopicNoLabel.setText("TopicNo");

        Person_IDLabel.setText("Person_ID");

        SearchTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchTextFieldActionPerformed(evt);
            }
        });

        SearchLinkButton.setBackground(new java.awt.Color(255, 255, 255));
        SearchLinkButton.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        SearchLinkButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Screen Shot 2018-03-16 at 12.23.15 PM.png"))); // NOI18N
        SearchLinkButton.setText("Search");
        SearchLinkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchLinkButtonActionPerformed(evt);
            }
        });

        AddLinkButton.setBackground(new java.awt.Color(255, 255, 255));
        AddLinkButton.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        AddLinkButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Screen Shot 2018-03-17 at 11.47.23 AM.png"))); // NOI18N
        AddLinkButton.setText("Add");
        AddLinkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddLinkButtonActionPerformed(evt);
            }
        });

        UpdateLinkButton.setBackground(new java.awt.Color(255, 255, 255));
        UpdateLinkButton.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        UpdateLinkButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Screen Shot 2018-03-17 at 11.50.32 AM.png"))); // NOI18N
        UpdateLinkButton.setText("Update");
        UpdateLinkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateLinkButtonActionPerformed(evt);
            }
        });

        DeleteLinkButton.setBackground(new java.awt.Color(255, 255, 255));
        DeleteLinkButton.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        DeleteLinkButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Screen Shot 2018-03-17 at 11.52.43 AM.png"))); // NOI18N
        DeleteLinkButton.setText("Delete");
        DeleteLinkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteLinkButtonActionPerformed(evt);
            }
        });

        BackToMenuButton.setBackground(new java.awt.Color(255, 255, 255));
        BackToMenuButton.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        BackToMenuButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Screen Shot 2018-03-16 at 12.20.01 PM.png"))); // NOI18N
        BackToMenuButton.setText("To menu");
        BackToMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackToMenuButtonActionPerformed(evt);
            }
        });

        LinkTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "LinkNo", "Person_ID", "TopicNo", "LevelOnTopic", "PassionLevel"
            }
        ));
        LinkTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LinkTableMouseClicked(evt);
            }
        });
        LinkTable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                LinkTableKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(LinkTable);

        LinkNoLabel.setText("LinkNo");

        PassionLevelLabel.setText("PassionLevel");

        PassionLeveljSpinner.setModel(new javax.swing.SpinnerListModel(new String[] {"1", "2", "3", "4", "5"}));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BackToMenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(SearchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(SearchLinkButton, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(AddLinkButton, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(UpdateLinkButton, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(DeleteLinkButton, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Person_IDLabel)
                                            .addComponent(TopicNoLabel)
                                            .addComponent(LinkNoLabel)
                                            .addComponent(LevelOnTopicLabel)
                                            .addComponent(PassionLevelLabel))
                                        .addGap(43, 43, 43)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Person_IDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(PassionLeveljSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(TopicNoTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(LevelOnTopicjSpinner, javax.swing.GroupLayout.Alignment.LEADING))
                                            .addComponent(LinkNoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(TitleLabel, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(TitleLabel)
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SearchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SearchLinkButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(LinkNoLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(LinkNoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Person_IDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Person_IDLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TopicNoLabel)
                            .addComponent(TopicNoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LevelOnTopicLabel)
                            .addComponent(LevelOnTopicjSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PassionLeveljSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PassionLevelLabel))
                        .addGap(18, 18, 18)
                        .addComponent(AddLinkButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(UpdateLinkButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DeleteLinkButton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BackToMenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SearchTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchTextFieldActionPerformed

    private void SearchLinkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchLinkButtonActionPerformed
       try{
            String sql = "select * from Link where LinkNo =?";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, SearchTextField.getText());
            ResultSet rs = pst.executeQuery();
            if(rs.next()){
                String add1 = rs.getString("LinkNo");
                LinkNoTextField.setText(add1);
                String add2 = rs.getString("Person_ID");
                Person_IDTextField.setText(add2);
                String add3 = rs.getString("TopicNo");
                TopicNoTextField.setText(add3);
                String add4 = rs.getString("LevelOnTopic");
                LevelOnTopicjSpinner.setValue(add4);
                String add5 = rs.getString("PassionLevel");
                PassionLeveljSpinner.setValue(add5);
                pst.close();
                rs.close();
            }
            else {
                JOptionPane.showMessageDialog(null, "There is no data under that LinkNo!" );
            }
            
            con.commit();
        }
        catch(SQLException e) {
            JOptionPane.showMessageDialog(null, e);

        }
    }//GEN-LAST:event_SearchLinkButtonActionPerformed

    private void AddLinkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddLinkButtonActionPerformed
        try{
            String sqladd = "INSERT into Link values(?,?,?,?,?)";
            PreparedStatement pst = con.prepareStatement(sqladd);
            pst.setInt(1, Integer.parseInt(LinkNoTextField.getText()));
            pst.setInt(2, Integer.parseInt(Person_IDTextField.getText()));
            pst.setInt(3, Integer.parseInt(TopicNoTextField.getText()));
            pst.setInt(4, Integer.parseInt((String) LevelOnTopicjSpinner.getValue()));
            pst.setInt(5, Integer.parseInt((String) PassionLeveljSpinner.getValue()));
            pst.execute();
            JOptionPane.showMessageDialog(null, "Added!");
            
            con.commit();
            
            //pst.close();
        }
        catch(HeadlessException | NumberFormatException | SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
        AddLinkButton.setEnabled(false);
        Link lk = new Link();
        lk.setVisible(true);
        dispose();
        //this.setVisible(false);
       
    }//GEN-LAST:event_AddLinkButtonActionPerformed

    private void UpdateLinkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateLinkButtonActionPerformed
       try{
           String value1 = LinkNoTextField.getText();
           String value2 = Person_IDTextField.getText();
           String value3 = TopicNoTextField.getText();
           String value4 = (String) LevelOnTopicjSpinner.getValue();
           String value5 = (String) PassionLeveljSpinner.getValue();
           String sql = "update Link set LinkNo ='"+value1+"', Person_ID ='"+value2+"', TopicNo = '"+value3+"', LevelOnTopic = '"+value4+"', PassionLevel = '"+value5+"' where LinkNo ='"+value1+"' ";
           PreparedStatement pst = con.prepareStatement(sql);
           pst.execute();
           JOptionPane.showMessageDialog(null, "Updated!");
           con.commit();
           
           //pst.close();
        } 
       catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(null, e);

        }
       UpdateLinkButton.setEnabled(false);
        Link lk = new Link();
        lk.setVisible(true);
        dispose();
        //this.setVisible(false);

    }//GEN-LAST:event_UpdateLinkButtonActionPerformed

    private void DeleteLinkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteLinkButtonActionPerformed
        try{
            String sql = "delete from Link where LinkNo =?";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, LinkNoTextField.getText());
            pst.execute();
            
            JOptionPane.showMessageDialog(null, "Deleted!");
            con.commit();
            
            //pst.close();

        } catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(null, e);

        }
        
        DeleteLinkButton.setEnabled(false);
        Link lk = new Link();
        lk.setVisible(true);
        dispose();
        //this.setVisible(false);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_DeleteLinkButtonActionPerformed

    private void BackToMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackToMenuButtonActionPerformed
        dispose();
        MainMenu mm = new MainMenu();
        mm.setVisible(true);
        //this.setVisible(false);        
// TODO add your handling code here:
    }//GEN-LAST:event_BackToMenuButtonActionPerformed

    private void LinkTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LinkTableMouseClicked
        int i = LinkTable.getSelectedRow();
        TableModel model = LinkTable.getModel();
        LinkNoTextField.setText(model.getValueAt(i, 0).toString());
        Person_IDTextField.setText(model.getValueAt(i, 1).toString());
        TopicNoTextField.setText(model.getValueAt(i, 2).toString());
        LevelOnTopicjSpinner.setValue(model.getValueAt(i, 3).toString());
        PassionLeveljSpinner.setValue(model.getValueAt(i, 4).toString());
    }//GEN-LAST:event_LinkTableMouseClicked

    private void LinkTableKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LinkTableKeyReleased
        int i = LinkTable.getSelectedRow();
        TableModel model = LinkTable.getModel();
        LinkNoTextField.setText(model.getValueAt(i, 0).toString());
        Person_IDTextField.setText(model.getValueAt(i, 1).toString());
        TopicNoTextField.setText(model.getValueAt(i, 2).toString());
        LevelOnTopicjSpinner.setValue(model.getValueAt(i, 3).toString());
        PassionLeveljSpinner.setValue(model.getValueAt(i, 4).toString());
    }//GEN-LAST:event_LinkTableKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Link.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Link.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Link.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Link.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Link().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddLinkButton;
    private javax.swing.JButton BackToMenuButton;
    private javax.swing.JButton DeleteLinkButton;
    private javax.swing.JLabel LevelOnTopicLabel;
    private javax.swing.JSpinner LevelOnTopicjSpinner;
    private javax.swing.JLabel LinkNoLabel;
    private javax.swing.JTextField LinkNoTextField;
    private javax.swing.JTable LinkTable;
    private javax.swing.JLabel PassionLevelLabel;
    private javax.swing.JSpinner PassionLeveljSpinner;
    private javax.swing.JLabel Person_IDLabel;
    private javax.swing.JTextField Person_IDTextField;
    private javax.swing.JButton SearchLinkButton;
    private javax.swing.JTextField SearchTextField;
    private javax.swing.JLabel TitleLabel;
    private javax.swing.JLabel TopicNoLabel;
    private javax.swing.JTextField TopicNoTextField;
    private javax.swing.JButton UpdateLinkButton;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner2;
    // End of variables declaration//GEN-END:variables
}
